vm:
  - size: 1G
  - type: linode
environment:
  TEST_VAL=42
post_install:
  stuff-service:
    - echo hello world
    - echo TEST_VAL is $TEST_VAL
    - echo domain is $DYNDEPLOY_DOMAIN
compose_files:
  - docker-compose-alternate.yml
  - docker-compose222.yml