      deployments:
  default:
    environment:
      TEST_VAL=42
    ready_wait: 120
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branch:
      TEST_VAL=42
    ready_wait:
      120
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    run_options: --env TEST_VAL2=${SQUASH_BRANCH_WITH_ID}
    context_path: ./stuff
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo branch id is $SQUASH_BRANCH_WITH_ID'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branchA:
    environment:
      TEST_VAL=4242
    ready_wait:
      120
    filename:
      ./stuff/DockerfileA
    dockerfileonly: true
    run_options: --env TEST_VAL2=43
    context_path: ./stuff
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branchB:
    environment:
      TEST_VAL=424242
    ready_wait:
      120
    filename:
      asdasd'asd';asf
    run_options: --env TEST_VAL2=${SQUASH_DOMAIN}
  post_launch:
    - target: 'stuff-service'
      command: exec
      docker: true
      options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
    - target: 'stuff-service'
      command: exec
      docker: true
      options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
