deployments:
  default:
    environment:
      TEST_VAL=42
    ready_wait: 120
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo branch id is $SQUASH_BRANCH_WITH_ID'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branch:
    environment:
      TEST_VAL=42
    ready_wait:
      120
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    run_options: --env TEST_VAL2=${SQUASH_BRANCH_WITH_ID}
    context_path: ./stuff
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo branch id is $SQUASH_BRANCH_WITH_ID'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branchDomain:
    environment:
      TEST_VAL=42
    domains: squash.io
    filename:
      ./stuff/Dockerfile
    context_path: ./stuff
  another_branch:
    environment:
      TEST_VAL=42
    domains: squash.io
    filename:
      ./stuff/Dockerfile
    context_path: ./stuff
    subdomains: test
  subdomains:
    environment:
      TEST_VAL=42
    filename:
      ./stuff/Dockerfile
    context_path: ./stuff
    subdomains:
      - test1
      - something
      - abc
  subdomains-no-default:
    environment: TEST_VAL=42
    default_pr_comment: false
    filename: ./stuff/Dockerfile
    context_path: ./stuff
    subdomains:
      header1:
        - something
        - abc
      header2:
        - a123
        - b456

