version: '3.1'
services:
  stuff-service:
    build:
        context: ./stuff
        dockerfile: Dockerfile-alternate
    ports:
      - 80:80
    environment:
      - TEST_VAL
      - SQUASH_DOMAIN
